### PR TITLE
Added Release action for GitHub

### PR DESCRIPTION
**Pull request by drkameleon**
Since [we were talking about it](https://github.com/h3rald/min/discussions/97) and I've ended up spending over 4 hours [trying to make it work for Arturo](https://github.com/arturo-lang/arturo/releases/tag/v0.9.6), I've though of just posting [a link of how I did it.](https://github.com/arturo-lang/arturo/releases/tag/v0.9.6)

But then, I thought: why not do it myself - or at least start it - and make a PR? :)

So... Tell me what you think! 

P.S. I'm not sure it works 100%, since I don't know the internals of min or its compilation (I haven't taken into account *lite* releases), but - given that I was based on your CI workflow and the work I did earlier on Arturo, it should be working (or after minimal effort...)

### CODE REVIEW

**Comment by h3rald** [comment]
Omg thanks a lot!!!

Looks fairly good, but I am probably gonna review it and test it out on a separate branch to see what happens.

Excellent work!

**Comment by drkameleon** [comment]
> Omg thanks a lot!!!
> 
> Looks fairly good, but I am probably gonna review it and test it out on a separate branch to see what happens.
> 
> Excellent work!

I think that's a great idea.

Do test it and let me know how it goes - in case I can assist in any way (not that I'm a Github Action guru... but trying.. :) )

**Comment by drkameleon** [comment]
Not too unrelated to the above, one of my ideas before I worked on Release workflows was to be able to provide "nightly" builds (that is: one build of the current development branch, done automatically every night).

Since I've finally managed to set this up as well, you'd might want to [have a look](https://github.com/arturo-lang/nightly). ;-)

**Comment by h3rald** [comment]
Ohh yes! That's a good idea, and probably also a good way to test the release workflow without messing up releases. Thanks again, looks great!

**Comment by drkameleon** [comment]
> to test the release workflow without messing up releases

Yep, exactly what I was thinking! :)

**Pull request merged**
