### PR TITLE
Add binary module

### PR DESCRIPTION
**Pull request by drkameleon**
Added module for Bitwise operations between integers + Unit tests:

- bitand
- bitnot
- bitor
- bitxor
- shl
- shr

(Feel free to rename any or all of them - or reject it altogether. I'm just experimenting a bit and given that your code is quite well-organized, it hasn't been that difficult ;-))

### CODE REVIEW

**Comment by h3rald** [comment]
Ohhh me likes! You're on fire today! 😱 

Even with unit tests, awesome. Only bit missing is the doc, but these should be really easy to document anyway. Thanks!

**Comment by drkameleon** [comment]
> Ohhh me likes! You're on fire today! 😱

Haha! Seems like it. I guess I decided to give myself a little open-source break (Arturo included) after weeks in-a-row of too work-oriented coding... :)

> Even with unit tests, awesome. Only bit missing is the doc, but these should be really easy to document anyway.

I'll have a look into it!

**Comment by drkameleon** [comment]
(not sure about the reference addition, but just took a shot at it ;-))

**Comment by h3rald** [comment]
That's it! Excellent! Thanks!! 👍

**Pull request merged**
