### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by SolitudeSF**
Fixed a `times` refactor and tightened integration with nimble so after merge it can be installed with just `nimble install 'https://github.com/h3rald/min@#head'`

### CODE REVIEW

**Comment by SolitudeSF** [comment]
ok, seems like you dont build nimble on travis. is this necessary?

**Comment by h3rald** [comment]
Hi! Thanks for your contributions!

Nope, at the moment min dependencies can typically be downloaded through nifty... I built nifty because I was literally unable to compile nimble in low-memory devices (e.g. Linux x86 with 500MB of ram).

I'd like to have the possibility to install min through nimble, but honestly I'd like to be an *option* not a requirement... Ideally I'd like to preserve the current nifty-based installation but also have the possibility to use nimble...

**Comment by SolitudeSF** [comment]
okay, i reverted to fetching deps with nifty, but nifty is still is a dependecy in nimble file so you can still install it with nimble.

**Comment by h3rald** [comment]
Excellent! Sounds like a good compromise, thanks!

**Comment by SolitudeSF** [comment]
i dont understand the travis error. the tests seem to be passing, but it segfaults in the end?

**Comment by h3rald** [comment]
Ah yes, that error seems to happen frequently on branches, but not as often on master. I should investigate it properly...

**Pull request merged**
