### PR TITLE
Fix typo in "clean.min" script

### PR DESCRIPTION
**Pull request by celtic-coder**

### CODE REVIEW

**Comment by celtic-coder** [comment]
**Note**: There are some warnings in the *Build* step of the [Check job](https://github.com/h3rald/min/pull/159/checks):

warnings-in-build-step

**Comment by celtic-coder** [comment]
Also, "zippy" is being installed twice giving the following error:

`Error: unhandled exception: EOF reached [EOFError]`

zippy-installed-twice

**Comment by h3rald** [comment]
Merged, thanks!

Yes, I didn't try rebuilding min with the current stable version of Nim, not much time available for my open source projects these days ☹️

**Comment by celtic-coder** [comment]
Given your limited time, thank you for addressing these details! 👍

**Pull request merged**
