### PR TITLE
documentation/code cleanup

### PR DESCRIPTION
**Pull request by jo-he**
Hi Fabio,

thanks for creating min! It's really fun to work with.

Between documentation and code, I found some discrepancies this commit addresses - besides some leftovers from older releases and typos.

Additionally, the examples in site/contents/reference-net.md are somehow broken beyond syntax. I couldn't mange to get them working with min 0.37.0. Seems that internally, file descriptors are not properly passed.

Regards,
Jo

### CODE REVIEW

**Comment by h3rald** [comment]
Thanks! Most of the corrections look fine, except one code change I am not sure was intended.

As for the net examples... they were working once, at least. What version of Nim did you use? Or did you try the pre-built executables? If so which OS?

**Comment by jo-he** [comment]
Well, actually all changes are intended. Which one are you referring to? Maybe the orphaned alias `=~` of the already removed `regex` operator?

The net examples fail at least with the pre-build Linux executable. E.g. using strace, I saw that 8192 (which looks more like a buffer size) was passed as file descriptor to send.

**Comment by jo-he** [comment]
Well, actually all changes are intended. Which one are you referring to? Maybe the orphaned alias `=~` of the already removed `regex` operator?

The net examples fail at least with the pre-build Linux executable. E.g. using strace, I saw that 8192 (which looks more like a buffer size) was passed as file descriptor to send.

**Comment by h3rald** [comment]
You are right! OK, all good then, merging... 

I will investigate the net examples. Thanks a lot for this!

**Comment by h3rald** [comment]
I tried the server example on my linux VPS running Ubuntu and the pre-built example works... or better, there are mistakes because the `=` sigil no longer exists (I'll fix that) so the `=srv` and `=cli` assignments have to be changed to `:srv` and `:cli` respectively, but other than that the server seems to start correctly at least.

**Comment by jo-he** [comment]
Thanks for merging! Meanwhile I couldn't reproduce the issue I had with the first two net examples (`connect`and `listen`). But, regarding the last one (`recv-line`), I'll open a proper issue.

**Pull request merged**
